# Cyclistic Data Cleaning - Wrangling

We're using the Data from September 2021 to September 2o22 so it's kind of a large data which is around 867 MB. First we need to read the data for each month seperately and then concate them in one dataframe and then we'll start cleaning and manupulating the dataset in order to visualize it on Tableau.

In [1]:
import pandas as pd
data_1 = pd.read_csv('Data/202109.csv')
data_1

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9DC7B962304CBFD8,electric_bike,2021-09-28 16:07:10,2021-09-28 16:09:54,NaN,NaN,NaN,NaN,41.890000,-87.680000,41.890000,-87.670000,casual
1,F930E2C6872D6B32,electric_bike,2021-09-28 14:24:51,2021-09-28 14:40:05,NaN,NaN,NaN,NaN,41.940000,-87.640000,41.980000,-87.670000,casual
2,6EF72137900BB910,electric_bike,2021-09-28 00:20:16,2021-09-28 00:23:57,NaN,NaN,NaN,NaN,41.810000,-87.720000,41.800000,-87.720000,casual
3,78D1DE133B3DBF55,electric_bike,2021-09-28 14:51:17,2021-09-28 15:00:06,NaN,NaN,NaN,NaN,41.800000,-87.720000,41.810000,-87.720000,casual
4,E03D4ACDCAEF6E00,electric_bike,2021-09-28 09:53:12,2021-09-28 10:03:44,NaN,NaN,NaN,NaN,41.880000,-87.740000,41.880000,-87.710000,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
756142,FA66BCAB0D73DDC2,classic_bike,2021-09-22 15:46:57,2021-09-22 16:01:15,Ellis Ave & 83rd St,584,Stony Island Ave & 75th St,KA1503000019,41.744123,-87.599034,41.758670,-87.586883,casual
756143,1D44DEFB5D36CA04,classic_bike,2021-09-25 16:25:23,2021-09-25 16:40:29,Ellis Ave & 60th St,KA1503000014,Shore Dr & 55th St,TA1308000009,41.785097,-87.601073,41.795212,-87.580715,casual
756144,6A346EA57FC23C45,classic_bike,2021-09-25 16:26:05,2021-09-25 16:40:30,Ellis Ave & 60th St,KA1503000014,Shore Dr & 55th St,TA1308000009,41.785097,-87.601073,41.795212,-87.580715,casual
756145,49360AFD771100A6,classic_bike,2021-09-15 17:57:48,2021-09-15 18:24:06,Ellis Ave & 60th St,KA1503000014,Shore Dr & 55th St,TA1308000009,41.785097,-87.601073,41.795212,-87.580715,casual
756146,343190A2DC023FED,electric_bike,2021-09-11 18:01:06,2021-09-11 18:08:26,Wells St & Huron St,TA1306000012,Clinton St & Lake St,13021,41.894887,-87.634343,41.885771,-87.641373,member

In [2]:
data_2 = pd.read_csv('Data/202110.csv')
data_2

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,620BC6107255BF4C,electric_bike,2021-10-22 12:46:42,2021-10-22 12:49:50,Kingsbury St & Kinzie St,KA1503000043,NaN,NaN,41.889186,-87.638495,41.890000,-87.630000,member
1,4471C70731AB2E45,electric_bike,2021-10-21 09:12:37,2021-10-21 09:14:14,NaN,NaN,NaN,NaN,41.930000,-87.700000,41.930000,-87.710000,member
2,26CA69D43D15EE14,electric_bike,2021-10-16 16:28:39,2021-10-16 16:36:26,NaN,NaN,NaN,NaN,41.920000,-87.700000,41.940000,-87.720000,member
3,362947F0437E1514,electric_bike,2021-10-16 16:17:48,2021-10-16 16:19:03,NaN,NaN,NaN,NaN,41.920000,-87.690000,41.920000,-87.690000,member
4,BB731DE2F2EC51C5,electric_bike,2021-10-20 23:17:54,2021-10-20 23:26:10,NaN,NaN,NaN,NaN,41.890000,-87.710000,41.890000,-87.690000,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
631221,BA077FDD42DABF12,classic_bike,2021-10-14 21:45:05,2021-10-14 22:07:25,Franklin St & Chicago Ave,13017,Michigan Ave & 14th St,TA1307000124,41.896747,-87.635668,41.864059,-87.623727,casual
631222,B7D99254E798AA6B,classic_bike,2021-10-02 15:28:28,2021-10-02 15:51:02,Streeter Dr & Grand Ave,13022,Michigan Ave & 14th St,TA1307000124,41.892278,-87.612043,41.864059,-87.623727,casual
631223,BCCFD66DA466400F,electric_bike,2021-10-08 16:47:10,2021-10-08 16:52:43,Calumet Ave & 21st St,15546,Michigan Ave & 14th St,TA1307000124,41.854055,-87.619187,41.864009,-87.623601,member
631224,623E0F6F50CDD6E4,classic_bike,2021-10-08 07:49:47,2021-10-08 07:55:15,Calumet Ave & 21st St,15546,Michigan Ave & 14th St,TA1307000124,41.854184,-87.619154,41.864059,-87.623727,member
631225,83FA6AC52B7B7A7B,classic_bike,2021-10-02 12:55:45,2021-10-02 13:21:10,Winthrop Ave & Lawrence Ave,TA1308000021,Sheffield Ave & Fullerton Ave,TA1306000016,41.968812,-87.657659,41.925602,-87.653708,member

In [3]:
data_3 = pd.read_csv('Data/202111.csv')
data_3

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7C00A93E10556E47,electric_bike,2021-11-27 13:27:38,2021-11-27 13:46:38,NaN,NaN,NaN,NaN,41.930000,-87.720000,41.96,-87.73,casual
1,90854840DFD508BA,electric_bike,2021-11-27 13:38:25,2021-11-27 13:56:10,NaN,NaN,NaN,NaN,41.960000,-87.700000,41.92,-87.70,casual
2,0A7D10CDD144061C,electric_bike,2021-11-26 22:03:34,2021-11-26 22:05:56,NaN,NaN,NaN,NaN,41.960000,-87.700000,41.96,-87.70,casual
3,2F3BE33085BCFF02,electric_bike,2021-11-27 09:56:49,2021-11-27 10:01:50,NaN,NaN,NaN,NaN,41.940000,-87.790000,41.93,-87.79,casual
4,D67B4781A19928D4,electric_bike,2021-11-26 19:09:28,2021-11-26 19:30:41,NaN,NaN,NaN,NaN,41.900000,-87.630000,41.88,-87.62,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359973,E00E9F3500D69BAA,electric_bike,2021-11-29 00:39:13,2021-11-29 00:51:41,Logan Blvd & Elston Ave,TA1308000031,NaN,NaN,41.929454,-87.684195,41.93,-87.72,member
359974,8EAA66CE314E5FF1,electric_bike,2021-11-03 13:56:33,2021-11-03 14:01:27,Logan Blvd & Elston Ave,TA1308000031,NaN,NaN,41.929440,-87.684180,41.94,-87.69,member
359975,36C2DC8BB1E13491,electric_bike,2021-11-02 19:32:18,2021-11-02 19:36:16,Logan Blvd & Elston Ave,TA1308000031,NaN,NaN,41.929452,-87.684135,41.94,-87.69,member
359976,8E42FE5C67DF6A96,electric_bike,2021-11-10 20:15:06,2021-11-10 20:22:01,Logan Blvd & Elston Ave,TA1308000031,NaN,NaN,41.929428,-87.684175,41.94,-87.69,member
359977,4F15069E2D2519BC,electric_bike,2021-11-30 20:18:00,2021-11-30 20:37:27,Ogden Ave & Chicago Ave,TA1305000020,NaN,NaN,41.896354,-87.653982,41.95,-87.70,member

In [4]:
data_4 = pd.read_csv('Data/202112.csv')
data_4

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,46F8167220E4431F,electric_bike,2021-12-07 15:06:07,2021-12-07 15:13:42,Laflin St & Cullerton St,13307,Morgan St & Polk St,TA1307000130,41.854833,-87.663660,41.871969,-87.650965,member
1,73A77762838B32FD,electric_bike,2021-12-11 03:43:29,2021-12-11 04:10:23,LaSalle Dr & Huron St,KP1705001026,Clarendon Ave & Leland Ave,TA1307000119,41.894405,-87.632331,41.967968,-87.650001,casual
2,4CF42452054F59C5,electric_bike,2021-12-15 23:10:28,2021-12-15 23:23:14,Halsted St & North Branch St,KA1504000117,Broadway & Barry Ave,13137,41.899357,-87.648522,41.937582,-87.644098,member
3,3278BA87BF698339,classic_bike,2021-12-26 16:16:10,2021-12-26 16:30:53,Halsted St & North Branch St,KA1504000117,LaSalle Dr & Huron St,KP1705001026,41.899390,-87.648545,41.894877,-87.632326,member
4,6FF54232576A3B73,electric_bike,2021-12-30 11:31:05,2021-12-30 11:51:21,Leavitt St & Chicago Ave,18058,Clark St & Drummond Pl,TA1307000142,41.895579,-87.682024,41.931248,-87.644336,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
247535,847431F3D5353AB7,electric_bike,2021-12-12 13:36:55,2021-12-12 13:56:08,Canal St & Madison St,13341,NaN,NaN,41.882289,-87.639752,41.890000,-87.610000,casual
247536,CF407BBC3B9FAD63,electric_bike,2021-12-06 19:37:50,2021-12-06 19:44:51,Canal St & Madison St,13341,Kingsbury St & Kinzie St,KA1503000043,41.882123,-87.640053,41.889106,-87.638862,member
247537,60BB69EBF5440E92,electric_bike,2021-12-02 08:57:04,2021-12-02 09:05:21,Canal St & Madison St,13341,Dearborn St & Monroe St,TA1305000006,41.881956,-87.639955,41.880254,-87.629603,member
247538,C414F654A28635B8,electric_bike,2021-12-13 09:00:26,2021-12-13 09:14:39,Lawndale Ave & 16th St,362.0,NaN,NaN,41.860000,-87.720000,41.850000,-87.710000,member
247539,37AC57E34B2E7E97,classic_bike,2021-12-13 08:45:32,2021-12-13 08:49:09,Michigan Ave & Jackson Blvd,TA1309000002,Dearborn St & Monroe St,TA1305000006,41.877850,-87.624080,41.881320,-87.629521,member

In [5]:
data_5 = pd.read_csv('Data/202201.csv')
data_5

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C2F7DD78E82EC875,electric_bike,2022-01-13 11:59:47,2022-01-13 12:02:44,Glenwood Ave & Touhy Ave,525,Clark St & Touhy Ave,RP-007,42.012800,-87.665906,42.012560,-87.674367,casual
1,A6CF8980A652D272,electric_bike,2022-01-10 08:41:56,2022-01-10 08:46:17,Glenwood Ave & Touhy Ave,525,Clark St & Touhy Ave,RP-007,42.012763,-87.665967,42.012560,-87.674367,casual
2,BD0F91DFF741C66D,classic_bike,2022-01-25 04:53:40,2022-01-25 04:58:01,Sheffield Ave & Fullerton Ave,TA1306000016,Greenview Ave & Fullerton Ave,TA1307000001,41.925602,-87.653708,41.925330,-87.665800,member
3,CBB80ED419105406,classic_bike,2022-01-04 00:18:04,2022-01-04 00:33:00,Clark St & Bryn Mawr Ave,KA1504000151,Paulina St & Montrose Ave,TA1309000021,41.983593,-87.669154,41.961507,-87.671387,casual
4,DDC963BFDDA51EEA,classic_bike,2022-01-20 01:31:10,2022-01-20 01:37:12,Michigan Ave & Jackson Blvd,TA1309000002,State St & Randolph St,TA1305000029,41.877850,-87.624080,41.884621,-87.627834,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103765,8788DA3EDE8FD8AB,electric_bike,2022-01-18 12:36:48,2022-01-18 12:46:19,Clinton St & Washington Blvd,WL-012,NaN,NaN,41.883436,-87.641391,41.890000,-87.620000,casual
103766,C6C3B64FDC827D8C,electric_bike,2022-01-27 11:00:06,2022-01-27 11:02:40,Racine Ave & Randolph St,13155,NaN,NaN,41.884158,-87.656977,41.880000,-87.650000,casual
103767,CA281AE7D8B06F5A,electric_bike,2022-01-10 16:14:51,2022-01-10 16:20:58,Broadway & Waveland Ave,13325,Clark St & Grace St,TA1307000127,41.949066,-87.648611,41.950780,-87.659172,casual
103768,44E348991862319B,electric_bike,2022-01-19 13:22:11,2022-01-19 13:24:27,Racine Ave & Randolph St,13155,NaN,NaN,41.884005,-87.657031,41.880000,-87.660000,casual
103769,E477C594A182AE58,electric_bike,2022-01-13 17:24:43,2022-01-13 17:28:14,Clinton St & Washington Blvd,WL-012,Desplaines St & Kinzie St,TA1306000003,41.883248,-87.641244,41.888716,-87.644448,casual

In [6]:
data_6 = pd.read_csv('Data/202202.csv')
data_6

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E1E065E7ED285C02,classic_bike,2022-02-19 18:08:41,2022-02-19 18:23:56,State St & Randolph St,TA1305000029,Clark St & Lincoln Ave,13179,41.884621,-87.627834,41.915689,-87.634600,member
1,1602DCDC5B30FFE3,classic_bike,2022-02-20 17:41:30,2022-02-20 17:45:56,Halsted St & Wrightwood Ave,TA1309000061,Southport Ave & Wrightwood Ave,TA1307000113,41.929143,-87.649077,41.928773,-87.663913,member
2,BE7DD2AF4B55C4AF,classic_bike,2022-02-25 18:55:56,2022-02-25 19:09:34,State St & Randolph St,TA1305000029,Canal St & Adams St,13011,41.884621,-87.627834,41.879255,-87.639904,member
3,A1789BDF844412BE,classic_bike,2022-02-14 11:57:03,2022-02-14 12:04:00,Southport Ave & Waveland Ave,13235,Broadway & Sheridan Rd,13323,41.948150,-87.663940,41.952833,-87.649993,member
4,07DE78092C62F7B3,classic_bike,2022-02-16 05:36:06,2022-02-16 05:39:00,State St & Randolph St,TA1305000029,Franklin St & Lake St,TA1307000111,41.884621,-87.627834,41.885837,-87.635500,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115604,211BE0DC162D85B7,electric_bike,2022-02-23 17:47:49,2022-02-23 18:02:29,NaN,NaN,Leavitt St & Chicago Ave,18058,41.880000,-87.630000,41.895501,-87.682017,member
115605,D4D53E78000C8CA1,electric_bike,2022-02-04 10:43:47,2022-02-04 10:50:52,NaN,NaN,Leavitt St & Chicago Ave,18058,41.910000,-87.680000,41.895501,-87.682017,member
115606,9E85F07D2F94492B,electric_bike,2022-02-28 09:16:33,2022-02-28 09:28:11,Wood St & Chicago Ave,637,Canal St & Adams St,13011,41.895714,-87.672210,41.879255,-87.639904,member
115607,B61B559F81F1D823,electric_bike,2022-02-10 16:55:16,2022-02-10 16:57:53,NaN,NaN,Canal St & Adams St,13011,41.880000,-87.630000,41.879255,-87.639904,member
115608,841C701610CF0609,electric_bike,2022-02-21 16:35:20,2022-02-21 16:42:53,NaN,NaN,Larrabee St & Oak St,KA1504000116,41.880000,-87.650000,41.900219,-87.642985,member

In [7]:
data_7 = pd.read_csv('Data/202203.csv')
data_7

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,47EC0A7F82E65D52,classic_bike,2022-03-21 13:45:01,2022-03-21 13:51:18,Wabash Ave & Wacker Pl,TA1307000131,Kingsbury St & Kinzie St,KA1503000043,41.886875,-87.626030,41.889177,-87.638506,member
1,8494861979B0F477,electric_bike,2022-03-16 09:37:16,2022-03-16 09:43:34,Michigan Ave & Oak St,13042,Orleans St & Chestnut St (NEXT Apts),620,41.900998,-87.623752,41.898203,-87.637536,member
2,EFE527AF80B66109,classic_bike,2022-03-23 19:52:02,2022-03-23 19:54:48,Broadway & Berwyn Ave,13109,Broadway & Ridge Ave,15578,41.978353,-87.659753,41.984045,-87.660274,member
3,9F446FD9DEE3F389,classic_bike,2022-03-01 19:12:26,2022-03-01 19:22:14,Wabash Ave & Wacker Pl,TA1307000131,Franklin St & Jackson Blvd,TA1305000025,41.886875,-87.626030,41.877708,-87.635321,member
4,431128AD9AFFEDC0,classic_bike,2022-03-21 18:37:01,2022-03-21 19:19:11,DuSable Lake Shore Dr & North Blvd,LF-005,Loomis St & Jackson Blvd,13206,41.911722,-87.626804,41.877945,-87.662007,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
284037,E23BE3DB740BE3B4,docked_bike,2022-03-13 16:31:03,2022-03-13 16:39:32,Michigan Ave & Oak St,13042,Streeter Dr & Grand Ave,13022,41.900960,-87.623777,41.892278,-87.612043,casual
284038,15AF71F3220F2A75,docked_bike,2022-03-09 06:56:02,2022-03-09 07:42:14,Broadway & Barry Ave,13137,Ravenswood Ave & Berteau Ave,TA1309000018,41.937582,-87.644098,41.957921,-87.673567,casual
284039,9C4CE6CC19F8225B,electric_bike,2022-03-09 15:55:26,2022-03-09 16:08:54,NaN,NaN,Albany Ave & Montrose Ave,15621,41.940000,-87.710000,41.961041,-87.705866,member
284040,F4E136DEF696F3AE,electric_bike,2022-03-21 16:12:44,2022-03-21 16:18:24,NaN,NaN,Larrabee St & Division St,KA1504000079,41.910000,-87.650000,41.903486,-87.643353,member
284041,5AEC5F39AF711895,classic_bike,2022-03-03 18:13:40,2022-03-03 18:23:39,Clark St & Randolph St,TA1305000030,Streeter Dr & Grand Ave,13022,41.884576,-87.631890,41.892278,-87.612043,member

In [8]:
data_8 = pd.read_csv('Data/202204.csv')
data_8

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,3564070EEFD12711,electric_bike,2022-04-06 17:42:48,2022-04-06 17:54:36,Paulina St & Howard St,515,University Library (NU),605,42.019135,-87.673532,42.052939,-87.673447,member
1,0B820C7FCF22F489,classic_bike,2022-04-24 19:23:07,2022-04-24 19:43:17,Wentworth Ave & Cermak Rd,13075,Green St & Madison St,TA1307000120,41.853085,-87.631931,41.881892,-87.648789,member
2,89EEEE32293F07FF,classic_bike,2022-04-20 19:29:08,2022-04-20 19:35:16,Halsted St & Polk St,TA1307000121,Green St & Madison St,TA1307000120,41.871840,-87.646640,41.881892,-87.648789,member
3,84D4751AEB31888D,classic_bike,2022-04-22 21:14:06,2022-04-22 21:23:29,Wentworth Ave & Cermak Rd,13075,Delano Ct & Roosevelt Rd,KA1706005007,41.853085,-87.631931,41.867491,-87.632190,casual
4,5664BCF0D1DE7A8B,electric_bike,2022-04-16 15:56:30,2022-04-16 16:02:11,Halsted St & Polk St,TA1307000121,Clinton St & Madison St,TA1305000032,41.871808,-87.646574,41.882242,-87.641066,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
371244,C5A123D7BF8D350A,electric_bike,2022-04-22 15:54:11,2022-04-22 16:20:59,Streeter Dr & Grand Ave,13022,California Ave & North Ave,13258,41.892296,-87.612198,41.910475,-87.696894,member
371245,F7FCC7C26D8D137D,electric_bike,2022-04-21 20:18:17,2022-04-21 20:46:45,Streeter Dr & Grand Ave,13022,California Ave & North Ave,13258,41.892295,-87.612323,41.910475,-87.696894,member
371246,43D351300A40000A,classic_bike,2022-04-21 16:46:02,2022-04-21 17:15:05,Franklin St & Monroe St,TA1309000007,St. Clair St & Erie St,13016,41.880317,-87.635185,41.894345,-87.622798,member
371247,1618BFEEA7B566EF,electric_bike,2022-04-16 13:19:44,2022-04-16 13:37:31,Ashland Ave & Blackhawk St,13224,Southport Ave & Waveland Ave,13235,41.907094,-87.667217,41.948150,-87.663940,casual
371248,92C069001A6B17B1,electric_bike,2022-04-21 18:06:41,2022-04-21 18:11:49,Southport Ave & Clark St,TA1308000047,Southport Ave & Waveland Ave,13235,41.957102,-87.664184,41.948150,-87.663940,casual

In [9]:
data_9 = pd.read_csv('Data/202205.csv')
data_9

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,EC2DE40644C6B0F4,classic_bike,2022-05-23 23:06:58,2022-05-23 23:40:19,Wabash Ave & Grand Ave,TA1307000117,Halsted St & Roscoe St,TA1309000025,41.891466,-87.626761,41.943670,-87.648950,member
1,1C31AD03897EE385,classic_bike,2022-05-11 08:53:28,2022-05-11 09:31:22,DuSable Lake Shore Dr & Monroe St,13300,Field Blvd & South Water St,15534,41.880958,-87.616743,41.886349,-87.617517,member
2,1542FBEC830415CF,classic_bike,2022-05-26 18:36:28,2022-05-26 18:58:18,Clinton St & Madison St,TA1305000032,Wood St & Milwaukee Ave,13221,41.882242,-87.641066,41.907655,-87.672552,member
3,6FF59852924528F8,classic_bike,2022-05-10 07:30:07,2022-05-10 07:38:49,Clinton St & Madison St,TA1305000032,Clark St & Randolph St,TA1305000030,41.882242,-87.641066,41.884576,-87.631890,member
4,483C52CAAE12E3AC,classic_bike,2022-05-10 17:31:56,2022-05-10 17:36:57,Clinton St & Madison St,TA1305000032,Morgan St & Lake St,TA1306000015,41.882242,-87.641066,41.885779,-87.651025,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
634853,8891BA0053ECEC4F,electric_bike,2022-05-27 22:00:02,2022-05-27 22:07:01,Clark St & Newport St,632,NaN,NaN,41.944557,-87.654830,41.920000,-87.650000,member
634854,47D8B5FBCADECFC1,electric_bike,2022-05-15 16:05:39,2022-05-15 16:44:12,Clark St & Newport St,632,NaN,NaN,41.944479,-87.654758,41.920000,-87.760000,member
634855,AA8D16CF38B40703,electric_bike,2022-05-21 10:10:13,2022-05-21 10:26:09,Francisco Ave & Bloomingdale Ave,429,NaN,NaN,41.910000,-87.700000,41.920000,-87.660000,casual
634856,897EBFD44F329E0A,electric_bike,2022-05-12 07:53:58,2022-05-12 08:01:18,Francisco Ave & Bloomingdale Ave,429,NaN,NaN,41.910000,-87.700000,41.900000,-87.690000,member
634857,AAC23AB89E8A7733,electric_bike,2022-05-11 21:14:28,2022-05-11 21:18:16,Clark St & Newport St,632,NaN,NaN,41.944567,-87.654802,41.940000,-87.650000,member

In [10]:
data_10 = pd.read_csv('Data/202206.csv')
data_10

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,600CFD130D0FD2A4,electric_bike,2022-06-30 17:27:53,2022-06-30 17:35:15,NaN,NaN,NaN,NaN,41.890000,-87.620000,41.910000,-87.620000,casual
1,F5E6B5C1682C6464,electric_bike,2022-06-30 18:39:52,2022-06-30 18:47:28,NaN,NaN,NaN,NaN,41.910000,-87.620000,41.930000,-87.630000,casual
2,B6EB6D27BAD771D2,electric_bike,2022-06-30 11:49:25,2022-06-30 12:02:54,NaN,NaN,NaN,NaN,41.910000,-87.650000,41.890000,-87.610000,casual
3,C9C320375DE1D5C6,electric_bike,2022-06-30 11:15:25,2022-06-30 11:19:43,NaN,NaN,NaN,NaN,41.800000,-87.660000,41.800000,-87.650000,casual
4,56C055851023BE98,electric_bike,2022-06-29 23:36:50,2022-06-29 23:45:17,NaN,NaN,NaN,NaN,41.910000,-87.630000,41.930000,-87.640000,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
769199,7B3B2890CA85E05D,classic_bike,2022-06-25 00:56:48,2022-06-25 01:01:39,Sheffield Ave & Kingsbury St,13154,Sheffield Ave & Kingsbury St,13154,41.910522,-87.653106,41.910522,-87.653106,member
769200,1E993989CC66BCBC,classic_bike,2022-06-25 00:56:25,2022-06-25 01:00:26,Sheffield Ave & Kingsbury St,13154,Sheffield Ave & Kingsbury St,13154,41.910522,-87.653106,41.910522,-87.653106,member
769201,AEA166296BC67566,electric_bike,2022-06-12 12:47:12,2022-06-12 12:47:36,Milwaukee Ave & Fullerton Ave,428,Milwaukee Ave & Fullerton Ave,428,41.920000,-87.700000,41.920000,-87.700000,casual
769202,B9F527742959CF03,classic_bike,2022-06-12 13:28:46,2022-06-12 13:53:11,Clark St & Randolph St,TA1305000030,Clark St & Randolph St,TA1305000030,41.884576,-87.631890,41.884576,-87.631890,casual
769203,D241310352E26484,classic_bike,2022-06-12 14:40:51,2022-06-12 15:08:14,Blue Island Ave & 18th St,13135,Blue Island Ave & 18th St,13135,41.857556,-87.661535,41.857556,-87.661535,casual

In [11]:
data_11 = pd.read_csv('Data/202207.csv')
data_11

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,954144C2F67B1932,classic_bike,2022-07-05 08:12:47,2022-07-05 08:24:32,Ashland Ave & Blackhawk St,13224,Kingsbury St & Kinzie St,KA1503000043,41.907066,-87.667252,41.889177,-87.638506,member
1,292E027607D218B6,classic_bike,2022-07-26 12:53:38,2022-07-26 12:55:31,Buckingham Fountain (Temp),15541,Michigan Ave & 8th St,623,41.869621,-87.623981,41.872773,-87.623981,casual
2,57765852588AD6E0,classic_bike,2022-07-03 13:58:49,2022-07-03 14:06:32,Buckingham Fountain (Temp),15541,Michigan Ave & 8th St,623,41.869621,-87.623981,41.872773,-87.623981,casual
3,B5B6BE44314590E6,classic_bike,2022-07-31 17:44:21,2022-07-31 18:42:50,Buckingham Fountain (Temp),15541,Woodlawn Ave & 55th St,TA1307000164,41.869621,-87.623981,41.795264,-87.596471,casual
4,A4C331F2A00E79E0,classic_bike,2022-07-13 19:49:06,2022-07-13 20:15:24,Wabash Ave & Grand Ave,TA1307000117,Sheffield Ave & Wellington Ave,TA1307000052,41.891466,-87.626761,41.936253,-87.652662,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
823483,605787F70B3B9FD3,electric_bike,2022-07-09 08:32:15,2022-07-09 08:56:10,NaN,NaN,NaN,NaN,41.740000,-87.680000,41.750000,-87.680000,member
823484,F0EECBEE637DF028,electric_bike,2022-07-17 13:27:57,2022-07-17 13:33:09,NaN,NaN,NaN,NaN,41.870000,-87.660000,41.870000,-87.680000,member
823485,B8B091DC72DDAB9D,electric_bike,2022-07-17 14:51:37,2022-07-17 14:57:01,NaN,NaN,NaN,NaN,41.950000,-87.640000,41.950000,-87.650000,member
823486,B4D3FFCC1F3AF5EC,electric_bike,2022-07-28 13:41:50,2022-07-28 13:47:17,NaN,NaN,NaN,NaN,41.880000,-87.630000,41.870000,-87.630000,member
823487,AA9217C8DA3BAC0B,electric_bike,2022-07-29 13:05:20,2022-07-29 13:10:40,NaN,NaN,NaN,NaN,41.900000,-87.660000,41.900000,-87.670000,member

In [12]:
data_12 = pd.read_csv('Data/202208.csv')
data_12

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,550CF7EFEAE0C618,electric_bike,2022-08-07 21:34:15,2022-08-07 21:41:46,NaN,NaN,NaN,NaN,41.930000,-87.690000,41.94,-87.72,casual
1,DAD198F405F9C5F5,electric_bike,2022-08-08 14:39:21,2022-08-08 14:53:23,NaN,NaN,NaN,NaN,41.890000,-87.640000,41.92,-87.64,casual
2,E6F2BC47B65CB7FD,electric_bike,2022-08-08 15:29:50,2022-08-08 15:40:34,NaN,NaN,NaN,NaN,41.970000,-87.690000,41.97,-87.66,casual
3,F597830181C2E13C,electric_bike,2022-08-08 02:43:50,2022-08-08 02:58:53,NaN,NaN,NaN,NaN,41.940000,-87.650000,41.97,-87.69,casual
4,0CE689BB4E313E8D,electric_bike,2022-08-07 20:24:06,2022-08-07 20:29:58,NaN,NaN,NaN,NaN,41.850000,-87.650000,41.84,-87.66,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
785927,EC17BE8AB1D73C88,electric_bike,2022-08-12 08:28:26,2022-08-12 08:42:26,Paulina St & Montrose Ave,TA1309000021,NaN,NaN,41.961563,-87.671431,41.94,-87.64,member
785928,57BAC0EA3A067A83,electric_bike,2022-08-22 12:30:19,2022-08-22 12:36:32,California Ave & 21st St,13096,NaN,NaN,41.853754,-87.695806,41.84,-87.69,member
785929,9B97FAE30276C299,electric_bike,2022-08-09 07:43:31,2022-08-09 07:50:50,Clinton St & Washington Blvd,WL-012,NaN,NaN,41.883404,-87.641222,41.89,-87.66,member
785930,2B4A9BA1E9AA9B51,electric_bike,2022-08-24 14:31:58,2022-08-24 14:40:32,Ashland Ave & Wellington Ave,13269,NaN,NaN,41.936081,-87.669896,41.93,-87.64,member
785931,7F0D048AC7C3B81A,electric_bike,2022-08-24 09:45:04,2022-08-24 09:45:19,Clark St & Lincoln Ave,13179,NaN,NaN,41.915784,-87.634676,41.92,-87.63,member

In [13]:
#Concated Dataset of all 12 Months
df = pd.concat([data_1, data_2, data_3, data_4, data_5, data_6, data_7, data_8, data_9, data_10, data_11, data_12])
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9DC7B962304CBFD8,electric_bike,2021-09-28 16:07:10,2021-09-28 16:09:54,NaN,NaN,NaN,NaN,41.890000,-87.680000,41.89,-87.67,casual
1,F930E2C6872D6B32,electric_bike,2021-09-28 14:24:51,2021-09-28 14:40:05,NaN,NaN,NaN,NaN,41.940000,-87.640000,41.98,-87.67,casual
2,6EF72137900BB910,electric_bike,2021-09-28 00:20:16,2021-09-28 00:23:57,NaN,NaN,NaN,NaN,41.810000,-87.720000,41.80,-87.72,casual
3,78D1DE133B3DBF55,electric_bike,2021-09-28 14:51:17,2021-09-28 15:00:06,NaN,NaN,NaN,NaN,41.800000,-87.720000,41.81,-87.72,casual
4,E03D4ACDCAEF6E00,electric_bike,2021-09-28 09:53:12,2021-09-28 10:03:44,NaN,NaN,NaN,NaN,41.880000,-87.740000,41.88,-87.71,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
785927,EC17BE8AB1D73C88,electric_bike,2022-08-12 08:28:26,2022-08-12 08:42:26,Paulina St & Montrose Ave,TA1309000021,NaN,NaN,41.961563,-87.671431,41.94,-87.64,member
785928,57BAC0EA3A067A83,electric_bike,2022-08-22 12:30:19,2022-08-22 12:36:32,California Ave & 21st St,13096,NaN,NaN,41.853754,-87.695806,41.84,-87.69,member
785929,9B97FAE30276C299,electric_bike,2022-08-09 07:43:31,2022-08-09 07:50:50,Clinton St & Washington Blvd,WL-012,NaN,NaN,41.883404,-87.641222,41.89,-87.66,member
785930,2B4A9BA1E9AA9B51,electric_bike,2022-08-24 14:31:58,2022-08-24 14:40:32,Ashland Ave & Wellington Ave,13269,NaN,NaN,41.936081,-87.669896,41.93,-87.64,member
785931,7F0D048AC7C3B81A,electric_bike,2022-08-24 09:45:04,2022-08-24 09:45:19,Clark St & Lincoln Ave,13179,NaN,NaN,41.915784,-87.634676,41.92,-87.63,member

# Checking fo Null values, duplicates and removing them

In [14]:
df.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    884365
start_station_id      884363
end_station_name      946303
end_station_id        946303
start_lat                  0
start_lng                  0
end_lat                 5727
end_lng                 5727
member_casual              0
dtype: int64

In [15]:
df_new = df.dropna(how='any',axis=0)
df_new

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
59,E92C804563F261EC,classic_bike,2021-09-05 01:25:08,2021-09-05 01:35:46,Wells St & Walton St,TA1306000011,Desplaines St & Kinzie St,TA1306000003,41.899930,-87.634430,41.888716,-87.644448,casual
61,9ECA91210441E847,classic_bike,2021-09-05 13:33:41,2021-09-05 14:06:08,Larrabee St & Armitage Ave,TA1309000006,Clark St & Leland Ave,TA1309000014,41.918084,-87.643749,41.967096,-87.667429,casual
153,3DAA144C4E85E3AA,classic_bike,2021-09-04 23:00:21,2021-09-04 23:10:00,Dearborn St & Monroe St,TA1305000006,Dearborn St & Monroe St,TA1305000006,41.881320,-87.629521,41.881320,-87.629521,casual
180,53B99FE9BD0D35F8,classic_bike,2021-09-14 16:25:16,2021-09-14 16:35:03,Kingsbury St & Kinzie St,KA1503000043,Orleans St & Elm St,TA1306000006,41.889177,-87.638506,41.902924,-87.637715,casual
182,2DB60C25C8CE3591,classic_bike,2021-09-13 22:34:54,2021-09-13 22:34:58,Michigan Ave & Oak St,13042,Michigan Ave & Oak St,13042,41.900960,-87.623777,41.900960,-87.623777,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
785874,986459A1B772B4DB,electric_bike,2022-08-02 08:22:10,2022-08-02 08:28:55,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900419,-87.696685,41.922695,-87.697153,casual
785892,305D447F43E64B00,electric_bike,2022-08-16 17:29:54,2022-08-16 17:46:16,Clinton St & Washington Blvd,WL-012,Wood St & Chicago Ave,637,41.883510,-87.641230,41.895634,-87.672069,casual
785894,CAE08BDD4D8D572E,electric_bike,2022-08-09 08:29:08,2022-08-09 08:35:52,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900350,-87.696709,41.922695,-87.697153,casual
785897,1F5B9F63085D6FE9,electric_bike,2022-08-09 17:55:27,2022-08-09 18:03:12,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900371,-87.696775,41.922695,-87.697153,casual
785902,97184CE7B4BA160B,electric_bike,2022-08-16 16:59:23,2022-08-16 17:50:03,Clark St & Lincoln Ave,13179,Wood St & Chicago Ave,637,41.915770,-87.634628,41.895634,-87.672069,casual

In [16]:
#reset index to start from 0 again
df_new = df_new.reset_index(drop=True)
df_new

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E92C804563F261EC,classic_bike,2021-09-05 01:25:08,2021-09-05 01:35:46,Wells St & Walton St,TA1306000011,Desplaines St & Kinzie St,TA1306000003,41.899930,-87.634430,41.888716,-87.644448,casual
1,9ECA91210441E847,classic_bike,2021-09-05 13:33:41,2021-09-05 14:06:08,Larrabee St & Armitage Ave,TA1309000006,Clark St & Leland Ave,TA1309000014,41.918084,-87.643749,41.967096,-87.667429,casual
2,3DAA144C4E85E3AA,classic_bike,2021-09-04 23:00:21,2021-09-04 23:10:00,Dearborn St & Monroe St,TA1305000006,Dearborn St & Monroe St,TA1305000006,41.881320,-87.629521,41.881320,-87.629521,casual
3,53B99FE9BD0D35F8,classic_bike,2021-09-14 16:25:16,2021-09-14 16:35:03,Kingsbury St & Kinzie St,KA1503000043,Orleans St & Elm St,TA1306000006,41.889177,-87.638506,41.902924,-87.637715,casual
4,2DB60C25C8CE3591,classic_bike,2021-09-13 22:34:54,2021-09-13 22:34:58,Michigan Ave & Oak St,13042,Michigan Ave & Oak St,13042,41.900960,-87.623777,41.900960,-87.623777,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4560141,986459A1B772B4DB,electric_bike,2022-08-02 08:22:10,2022-08-02 08:28:55,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900419,-87.696685,41.922695,-87.697153,casual
4560142,305D447F43E64B00,electric_bike,2022-08-16 17:29:54,2022-08-16 17:46:16,Clinton St & Washington Blvd,WL-012,Wood St & Chicago Ave,637,41.883510,-87.641230,41.895634,-87.672069,casual
4560143,CAE08BDD4D8D572E,electric_bike,2022-08-09 08:29:08,2022-08-09 08:35:52,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900350,-87.696709,41.922695,-87.697153,casual
4560144,1F5B9F63085D6FE9,electric_bike,2022-08-09 17:55:27,2022-08-09 18:03:12,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900371,-87.696775,41.922695,-87.697153,casual
4560145,97184CE7B4BA160B,electric_bike,2022-08-16 16:59:23,2022-08-16 17:50:03,Clark St & Lincoln Ave,13179,Wood St & Chicago Ave,637,41.915770,-87.634628,41.895634,-87.672069,casual

## Check Duplicates

In [17]:
df_new.duplicated().any()

False

# Check the Data types of columns and Change them

Since started_at and ended_at are objects here we have change the data type to datetime in order to calculate length of the ride. Also ride_type and member_casual are categorical data so we'll change their data type into category.

In [18]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4560146 entries, 0 to 4560145
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 452.3+ MB

In [19]:
df_new["started_at"] = pd.to_datetime(df_new["started_at"])
df_new["started_at"]

0         2021-09-05 01:25:08
1         2021-09-05 13:33:41
2         2021-09-04 23:00:21
3         2021-09-14 16:25:16
4         2021-09-13 22:34:54
                  ...
4560141   2022-08-02 08:22:10
4560142   2022-08-16 17:29:54
4560143   2022-08-09 08:29:08
4560144   2022-08-09 17:55:27
4560145   2022-08-16 16:59:23
Name: started_at, Length: 4560146, dtype: datetime64[ns]

In [20]:
df_new["ended_at"] = pd.to_datetime(df_new["ended_at"])
df_new["ended_at"]

0         2021-09-05 01:35:46
1         2021-09-05 14:06:08
2         2021-09-04 23:10:00
3         2021-09-14 16:35:03
4         2021-09-13 22:34:58
                  ...
4560141   2022-08-02 08:28:55
4560142   2022-08-16 17:46:16
4560143   2022-08-09 08:35:52
4560144   2022-08-09 18:03:12
4560145   2022-08-16 17:50:03
Name: ended_at, Length: 4560146, dtype: datetime64[ns]

In [21]:
df_new = df_new.astype({"rideable_type":"category", "member_casual":"category"})
df_new

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E92C804563F261EC,classic_bike,2021-09-05 01:25:08,2021-09-05 01:35:46,Wells St & Walton St,TA1306000011,Desplaines St & Kinzie St,TA1306000003,41.899930,-87.634430,41.888716,-87.644448,casual
1,9ECA91210441E847,classic_bike,2021-09-05 13:33:41,2021-09-05 14:06:08,Larrabee St & Armitage Ave,TA1309000006,Clark St & Leland Ave,TA1309000014,41.918084,-87.643749,41.967096,-87.667429,casual
2,3DAA144C4E85E3AA,classic_bike,2021-09-04 23:00:21,2021-09-04 23:10:00,Dearborn St & Monroe St,TA1305000006,Dearborn St & Monroe St,TA1305000006,41.881320,-87.629521,41.881320,-87.629521,casual
3,53B99FE9BD0D35F8,classic_bike,2021-09-14 16:25:16,2021-09-14 16:35:03,Kingsbury St & Kinzie St,KA1503000043,Orleans St & Elm St,TA1306000006,41.889177,-87.638506,41.902924,-87.637715,casual
4,2DB60C25C8CE3591,classic_bike,2021-09-13 22:34:54,2021-09-13 22:34:58,Michigan Ave & Oak St,13042,Michigan Ave & Oak St,13042,41.900960,-87.623777,41.900960,-87.623777,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4560141,986459A1B772B4DB,electric_bike,2022-08-02 08:22:10,2022-08-02 08:28:55,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900419,-87.696685,41.922695,-87.697153,casual
4560142,305D447F43E64B00,electric_bike,2022-08-16 17:29:54,2022-08-16 17:46:16,Clinton St & Washington Blvd,WL-012,Wood St & Chicago Ave,637,41.883510,-87.641230,41.895634,-87.672069,casual
4560143,CAE08BDD4D8D572E,electric_bike,2022-08-09 08:29:08,2022-08-09 08:35:52,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900350,-87.696709,41.922695,-87.697153,casual
4560144,1F5B9F63085D6FE9,electric_bike,2022-08-09 17:55:27,2022-08-09 18:03:12,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900371,-87.696775,41.922695,-87.697153,casual
4560145,97184CE7B4BA160B,electric_bike,2022-08-16 16:59:23,2022-08-16 17:50:03,Clark St & Lincoln Ave,13179,Wood St & Chicago Ave,637,41.915770,-87.634628,41.895634,-87.672069,casual

## Change the Column name

In [22]:
#Rename member_casual column
df_new['member_type']= df_new['member_casual']
df_new['member_type']

0          casual
1          casual
2          casual
3          casual
4          casual
            ...
4560141    casual
4560142    casual
4560143    casual
4560144    casual
4560145    casual
Name: member_type, Length: 4560146, dtype: category
Categories (2, object): ['casual', 'member']

# Calculate the Ride Length and Drop Negative Values

In [23]:
#Instead of showing the ride length by the datetime we can show it also hear in minutes
df_new['ride_length'] = round((df_new['ended_at'] - df_new['started_at']).dt.total_seconds() / 60, 2)
df_new['ride_length']

0          10.63
1          32.45
2           9.65
3           9.78
4           0.07
           ...
4560141     6.75
4560142    16.37
4560143     6.73
4560144     7.75
4560145    50.67
Name: ride_length, Length: 4560146, dtype: float64

In [24]:
#Removing the negative ride lengths
df_new= df_new[df_new['ride_length'] >= 0]
df_new

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,member_type,ride_length
0,E92C804563F261EC,classic_bike,2021-09-05 01:25:08,2021-09-05 01:35:46,Wells St & Walton St,TA1306000011,Desplaines St & Kinzie St,TA1306000003,41.899930,-87.634430,41.888716,-87.644448,casual,casual,10.63
1,9ECA91210441E847,classic_bike,2021-09-05 13:33:41,2021-09-05 14:06:08,Larrabee St & Armitage Ave,TA1309000006,Clark St & Leland Ave,TA1309000014,41.918084,-87.643749,41.967096,-87.667429,casual,casual,32.45
2,3DAA144C4E85E3AA,classic_bike,2021-09-04 23:00:21,2021-09-04 23:10:00,Dearborn St & Monroe St,TA1305000006,Dearborn St & Monroe St,TA1305000006,41.881320,-87.629521,41.881320,-87.629521,casual,casual,9.65
3,53B99FE9BD0D35F8,classic_bike,2021-09-14 16:25:16,2021-09-14 16:35:03,Kingsbury St & Kinzie St,KA1503000043,Orleans St & Elm St,TA1306000006,41.889177,-87.638506,41.902924,-87.637715,casual,casual,9.78
4,2DB60C25C8CE3591,classic_bike,2021-09-13 22:34:54,2021-09-13 22:34:58,Michigan Ave & Oak St,13042,Michigan Ave & Oak St,13042,41.900960,-87.623777,41.900960,-87.623777,casual,casual,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4560141,986459A1B772B4DB,electric_bike,2022-08-02 08:22:10,2022-08-02 08:28:55,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900419,-87.696685,41.922695,-87.697153,casual,casual,6.75
4560142,305D447F43E64B00,electric_bike,2022-08-16 17:29:54,2022-08-16 17:46:16,Clinton St & Washington Blvd,WL-012,Wood St & Chicago Ave,637,41.883510,-87.641230,41.895634,-87.672069,casual,casual,16.37
4560143,CAE08BDD4D8D572E,electric_bike,2022-08-09 08:29:08,2022-08-09 08:35:52,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900350,-87.696709,41.922695,-87.697153,casual,casual,6.73
4560144,1F5B9F63085D6FE9,electric_bike,2022-08-09 17:55:27,2022-08-09 18:03:12,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900371,-87.696775,41.922695,-87.697153,casual,casual,7.75
4560145,97184CE7B4BA160B,electric_bike,2022-08-16 16:59:23,2022-08-16 17:50:03,Clark St & Lincoln Ave,13179,Wood St & Chicago Ave,637,41.915770,-87.634628,41.895634,-87.672069,casual,casual,50.67

In [25]:
#I dropped the rides under one minute because the rides under a minute are mostly a mistake by the customer.
df_new = df_new[df_new['ride_length'] >= 1]
df_new

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,member_type,ride_length
0,E92C804563F261EC,classic_bike,2021-09-05 01:25:08,2021-09-05 01:35:46,Wells St & Walton St,TA1306000011,Desplaines St & Kinzie St,TA1306000003,41.899930,-87.634430,41.888716,-87.644448,casual,casual,10.63
1,9ECA91210441E847,classic_bike,2021-09-05 13:33:41,2021-09-05 14:06:08,Larrabee St & Armitage Ave,TA1309000006,Clark St & Leland Ave,TA1309000014,41.918084,-87.643749,41.967096,-87.667429,casual,casual,32.45
2,3DAA144C4E85E3AA,classic_bike,2021-09-04 23:00:21,2021-09-04 23:10:00,Dearborn St & Monroe St,TA1305000006,Dearborn St & Monroe St,TA1305000006,41.881320,-87.629521,41.881320,-87.629521,casual,casual,9.65
3,53B99FE9BD0D35F8,classic_bike,2021-09-14 16:25:16,2021-09-14 16:35:03,Kingsbury St & Kinzie St,KA1503000043,Orleans St & Elm St,TA1306000006,41.889177,-87.638506,41.902924,-87.637715,casual,casual,9.78
6,F79ECB90D812BB9F,classic_bike,2021-09-04 13:59:35,2021-09-04 16:04:01,Michigan Ave & Oak St,13042,Michigan Ave & Oak St,13042,41.900960,-87.623777,41.900960,-87.623777,casual,casual,124.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4560141,986459A1B772B4DB,electric_bike,2022-08-02 08:22:10,2022-08-02 08:28:55,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900419,-87.696685,41.922695,-87.697153,casual,casual,6.75
4560142,305D447F43E64B00,electric_bike,2022-08-16 17:29:54,2022-08-16 17:46:16,Clinton St & Washington Blvd,WL-012,Wood St & Chicago Ave,637,41.883510,-87.641230,41.895634,-87.672069,casual,casual,16.37
4560143,CAE08BDD4D8D572E,electric_bike,2022-08-09 08:29:08,2022-08-09 08:35:52,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900350,-87.696709,41.922695,-87.697153,casual,casual,6.73
4560144,1F5B9F63085D6FE9,electric_bike,2022-08-09 17:55:27,2022-08-09 18:03:12,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900371,-87.696775,41.922695,-87.697153,casual,casual,7.75
4560145,97184CE7B4BA160B,electric_bike,2022-08-16 16:59:23,2022-08-16 17:50:03,Clark St & Lincoln Ave,13179,Wood St & Chicago Ave,637,41.915770,-87.634628,41.895634,-87.672069,casual,casual,50.67

In [26]:
# It seems like many rows in columns has negative values because ending time started earlier than starting time.
df_new["ride_length"].describe(include = "all")

count    4.488333e+06
mean     1.828069e+01
std      7.594897e+01
min      1.000000e+00
25%      6.480000e+00
50%      1.118000e+01
75%      1.997000e+01
max      4.070502e+04
Name: ride_length, dtype: float64

# Calculate the Trip Distance

In [27]:
import numpy as np
#df_new["ride_distance"] = np.sqrt(((df_new["end_lat"] -df_new["start_lat"])**2) + ((df_new["end_lng"] - df_new["start_lng"])**2))
#df_new["ride_distance"] = df_new["ride_distance"] * 6373 #distance in kms
#df_new["ride_distance"]

In [28]:
import math

In [29]:
df_new['lat'] = (df_new['end_lat'] - df_new['start_lat'])
df_new['lng'] = (df_new['end_lng']) - df_new['start_lng']

/var/folders/c3/pkgzz_891b148813l5gzlgl40000gn/T/ipykernel_7967/4219292120.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['lat'] = (df_new['end_lat'] - df_new['start_lat'])
/var/folders/c3/pkgzz_891b148813l5gzlgl40000gn/T/ipykernel_7967/4219292120.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['lng'] = (df_new['end_lng']) - df_new['start_lng']

In [30]:
df_new["ride_distance"]= np.sqrt((df_new['lat']** 2) + (df_new['lng'] ** 2))

/var/folders/c3/pkgzz_891b148813l5gzlgl40000gn/T/ipykernel_7967/714263738.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["ride_distance"]= np.sqrt((df_new['lat']** 2) + (df_new['lng'] ** 2))

In [31]:
df_new["ride_distance"]= df_new["ride_distance"] * 111
df_new["ride_distance"]

/var/folders/c3/pkgzz_891b148813l5gzlgl40000gn/T/ipykernel_7967/3466848663.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new["ride_distance"]= df_new["ride_distance"] * 111

0          1.669099
1          6.042029
2          0.000000
3          1.528458
6          0.000000
             ...
4560141    2.473144
4560142    3.678178
4560143    2.480766
4560144    2.478300
4560145    4.718863
Name: ride_distance, Length: 4488333, dtype: float64

# Show the Day,  Month and the Season of the Ride

In [32]:
#Extracting the hour
df_new['time_of_day'] = df_new['started_at'].dt.hour
df_new = df_new.astype({'time_of_day':'int8'})
df_new

/var/folders/c3/pkgzz_891b148813l5gzlgl40000gn/T/ipykernel_7967/94466715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['time_of_day'] = df_new['started_at'].dt.hour

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,member_type,ride_length,lat,lng,ride_distance,time_of_day
0,E92C804563F261EC,classic_bike,2021-09-05 01:25:08,2021-09-05 01:35:46,Wells St & Walton St,TA1306000011,Desplaines St & Kinzie St,TA1306000003,41.899930,-87.634430,41.888716,-87.644448,casual,casual,10.63,-0.011214,-0.010018,1.669099,1
1,9ECA91210441E847,classic_bike,2021-09-05 13:33:41,2021-09-05 14:06:08,Larrabee St & Armitage Ave,TA1309000006,Clark St & Leland Ave,TA1309000014,41.918084,-87.643749,41.967096,-87.667429,casual,casual,32.45,0.049012,-0.023680,6.042029,13
2,3DAA144C4E85E3AA,classic_bike,2021-09-04 23:00:21,2021-09-04 23:10:00,Dearborn St & Monroe St,TA1305000006,Dearborn St & Monroe St,TA1305000006,41.881320,-87.629521,41.881320,-87.629521,casual,casual,9.65,0.000000,0.000000,0.000000,23
3,53B99FE9BD0D35F8,classic_bike,2021-09-14 16:25:16,2021-09-14 16:35:03,Kingsbury St & Kinzie St,KA1503000043,Orleans St & Elm St,TA1306000006,41.889177,-87.638506,41.902924,-87.637715,casual,casual,9.78,0.013747,0.000791,1.528458,16
6,F79ECB90D812BB9F,classic_bike,2021-09-04 13:59:35,2021-09-04 16:04:01,Michigan Ave & Oak St,13042,Michigan Ave & Oak St,13042,41.900960,-87.623777,41.900960,-87.623777,casual,casual,124.43,0.000000,0.000000,0.000000,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4560141,986459A1B772B4DB,electric_bike,2022-08-02 08:22:10,2022-08-02 08:28:55,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900419,-87.696685,41.922695,-87.697153,casual,casual,6.75,0.022276,-0.000468,2.473144,8
4560142,305D447F43E64B00,electric_bike,2022-08-16 17:29:54,2022-08-16 17:46:16,Clinton St & Washington Blvd,WL-012,Wood St & Chicago Ave,637,41.883510,-87.641230,41.895634,-87.672069,casual,casual,16.37,0.012124,-0.030839,3.678178,17
4560143,CAE08BDD4D8D572E,electric_bike,2022-08-09 08:29:08,2022-08-09 08:35:52,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900350,-87.696709,41.922695,-87.697153,casual,casual,6.73,0.022345,-0.000444,2.480766,8
4560144,1F5B9F63085D6FE9,electric_bike,2022-08-09 17:55:27,2022-08-09 18:03:12,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900371,-87.696775,41.922695,-87.697153,casual,casual,7.75,0.022324,-0.000378,2.478300,17
4560145,97184CE7B4BA160B,electric_bike,2022-08-16 16:59:23,2022-08-16 17:50:03,Clark St & Lincoln Ave,13179,Wood St & Chicago Ave,637,41.915770,-87.634628,41.895634,-87.672069,casual,casual,50.67,-0.020136,-0.037441,4.718863,16

In [33]:
#to find out which days where the busiest we have to show the day of the ride
import pandas as pd
from pandas.api.types import CategoricalDtype
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
df_new['day_of_week'] = df_new['started_at'].dt.day_name()
df_new['day_of_week'] = df_new['day_of_week'].astype(CategoricalDtype(categories=days, ordered=False))

In [34]:
# Add column for the month the ride started 
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
df_new['month'] = df_new['started_at'].dt.month_name()
df_new['month'] = df_new['month'].astype(CategoricalDtype(categories=months,ordered=False))
display(df_new.head(10))

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,member_type,ride_length,lat,lng,ride_distance,time_of_day,day_of_week,month
0,E92C804563F261EC,classic_bike,2021-09-05 01:25:08,2021-09-05 01:35:46,Wells St & Walton St,TA1306000011,Desplaines St & Kinzie St,TA1306000003,41.899930,-87.634430,...,-87.644448,casual,casual,10.63,-0.011214,-0.010018,1.669099,1,Sunday,September
1,9ECA91210441E847,classic_bike,2021-09-05 13:33:41,2021-09-05 14:06:08,Larrabee St & Armitage Ave,TA1309000006,Clark St & Leland Ave,TA1309000014,41.918084,-87.643749,...,-87.667429,casual,casual,32.45,0.049012,-0.023680,6.042029,13,Sunday,September
2,3DAA144C4E85E3AA,classic_bike,2021-09-04 23:00:21,2021-09-04 23:10:00,Dearborn St & Monroe St,TA1305000006,Dearborn St & Monroe St,TA1305000006,41.881320,-87.629521,...,-87.629521,casual,casual,9.65,0.000000,0.000000,0.000000,23,Saturday,September
3,53B99FE9BD0D35F8,classic_bike,2021-09-14 16:25:16,2021-09-14 16:35:03,Kingsbury St & Kinzie St,KA1503000043,Orleans St & Elm St,TA1306000006,41.889177,-87.638506,...,-87.637715,casual,casual,9.78,0.013747,0.000791,1.528458,16,Tuesday,September
6,F79ECB90D812BB9F,classic_bike,2021-09-04 13:59:35,2021-09-04 16:04:01,Michigan Ave & Oak St,13042,Michigan Ave & Oak St,13042,41.900960,-87.623777,...,-87.623777,casual,casual,124.43,0.000000,0.000000,0.000000,13,Saturday,September
7,2E3BB46763882E6A,electric_bike,2021-09-21 07:36:27,2021-09-21 07:43:23,Kingsbury St & Kinzie St,KA1503000043,Dearborn St & Monroe St,TA1305000006,41.889162,-87.638466,...,-87.629968,casual,casual,6.93,-0.007528,0.008498,1.260206,7,Tuesday,September
8,11F80F9DEA208F94,electric_bike,2021-09-13 07:28:52,2021-09-13 07:36:01,Kingsbury St & Kinzie St,KA1503000043,Dearborn St & Monroe St,TA1305000006,41.889139,-87.638332,...,-87.630193,casual,casual,7.15,-0.007199,0.008139,1.206144,7,Monday,September
9,C2B0AF6849A4ACA9,electric_bike,2021-09-11 01:13:34,2021-09-11 01:18:12,Clark St & Grace St,TA1307000127,Clark St & Leland Ave,TA1309000014,41.950909,-87.659111,...,-87.667399,casual,casual,4.63,0.016181,-0.008288,2.018015,1,Saturday,September
10,7E864223899FC4AA,classic_bike,2021-09-13 18:38:11,2021-09-13 19:07:28,Michigan Ave & Oak St,13042,Michigan Ave & Oak St,13042,41.900960,-87.623777,...,-87.623777,casual,casual,29.28,0.000000,0.000000,0.000000,18,Monday,September
11,B50E847794DEAEA0,electric_bike,2021-09-12 08:39:26,2021-09-12 09:12:41,Larrabee St & Armitage Ave,TA1309000006,Larrabee St & Armitage Ave,TA1309000006,41.918143,-87.643784,...,-87.643818,casual,casual,33.25,-0.000079,-0.000034,0.009564,8,Sunday,September

In [35]:
df_new['month'].isna().sum()

0

In [36]:
#defining the seasons
season_dict = {'January': 'Winter',
               'February': 'Winter',
               'March': 'Spring', 
               'April': 'Spring',
               'May': 'Spring',
               'June': 'Summer',
               'July': 'Summer',
               'August': 'Summer',
               'September': 'Fall',
               'October': 'Fall',
               'November': 'Fall',
               'December': 'Winter'}
df_new['season'] = df_new['month'].apply(lambda x: season_dict[x])

In [37]:
df_new['season']

0            Fall
1            Fall
2            Fall
3            Fall
6            Fall
            ...
4560141    Summer
4560142    Summer
4560143    Summer
4560144    Summer
4560145    Summer
Name: season, Length: 4488333, dtype: object

In [38]:
df_new['season'].value_counts()

Summer    1835053
Fall      1337018
Spring     975545
Winter     340717
Name: season, dtype: int64

In [39]:
df_new = df_new.astype({"season":"category"})
df_new

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,member_type,ride_length,lat,lng,ride_distance,time_of_day,day_of_week,month,season
0,E92C804563F261EC,classic_bike,2021-09-05 01:25:08,2021-09-05 01:35:46,Wells St & Walton St,TA1306000011,Desplaines St & Kinzie St,TA1306000003,41.899930,-87.634430,...,casual,casual,10.63,-0.011214,-0.010018,1.669099,1,Sunday,September,Fall
1,9ECA91210441E847,classic_bike,2021-09-05 13:33:41,2021-09-05 14:06:08,Larrabee St & Armitage Ave,TA1309000006,Clark St & Leland Ave,TA1309000014,41.918084,-87.643749,...,casual,casual,32.45,0.049012,-0.023680,6.042029,13,Sunday,September,Fall
2,3DAA144C4E85E3AA,classic_bike,2021-09-04 23:00:21,2021-09-04 23:10:00,Dearborn St & Monroe St,TA1305000006,Dearborn St & Monroe St,TA1305000006,41.881320,-87.629521,...,casual,casual,9.65,0.000000,0.000000,0.000000,23,Saturday,September,Fall
3,53B99FE9BD0D35F8,classic_bike,2021-09-14 16:25:16,2021-09-14 16:35:03,Kingsbury St & Kinzie St,KA1503000043,Orleans St & Elm St,TA1306000006,41.889177,-87.638506,...,casual,casual,9.78,0.013747,0.000791,1.528458,16,Tuesday,September,Fall
6,F79ECB90D812BB9F,classic_bike,2021-09-04 13:59:35,2021-09-04 16:04:01,Michigan Ave & Oak St,13042,Michigan Ave & Oak St,13042,41.900960,-87.623777,...,casual,casual,124.43,0.000000,0.000000,0.000000,13,Saturday,September,Fall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4560141,986459A1B772B4DB,electric_bike,2022-08-02 08:22:10,2022-08-02 08:28:55,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900419,-87.696685,...,casual,casual,6.75,0.022276,-0.000468,2.473144,8,Tuesday,August,Summer
4560142,305D447F43E64B00,electric_bike,2022-08-16 17:29:54,2022-08-16 17:46:16,Clinton St & Washington Blvd,WL-012,Wood St & Chicago Ave,637,41.883510,-87.641230,...,casual,casual,16.37,0.012124,-0.030839,3.678178,17,Tuesday,August,Summer
4560143,CAE08BDD4D8D572E,electric_bike,2022-08-09 08:29:08,2022-08-09 08:35:52,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900350,-87.696709,...,casual,casual,6.73,0.022345,-0.000444,2.480766,8,Tuesday,August,Summer
4560144,1F5B9F63085D6FE9,electric_bike,2022-08-09 17:55:27,2022-08-09 18:03:12,California Ave & Cortez St,17660,California Ave & Milwaukee Ave,13084,41.900371,-87.696775,...,casual,casual,7.75,0.022324,-0.000378,2.478300,17,Tuesday,August,Summer
4560145,97184CE7B4BA160B,electric_bike,2022-08-16 16:59:23,2022-08-16 17:50:03,Clark St & Lincoln Ave,13179,Wood St & Chicago Ave,637,41.915770,-87.634628,...,casual,casual,50.67,-0.020136,-0.037441,4.718863,16,Tuesday,August,Summer

In [40]:
station_name = df_new.start_station_name.unique().tolist()
station_name.sort()
station_name

['10101 S Stony Island Ave',
 '111th St - Morgan Park Metra',
 '2112 W Peterson Ave',
 '532 E 43rd St',
 '63rd & Western Ave - north corner',
 '63rd & Western Ave - south corner',
 '63rd St Beach',
 '83rd St (Avalon Park) Metra',
 '900 W Harrison St',
 'Abbott Park',
 'Aberdeen St & Jackson Blvd',
 'Aberdeen St & Monroe St',
 'Aberdeen St & Randolph St',
 'Ada St & 113th St',
 'Ada St & 117th St',
 'Ada St & 79th St',
 'Ada St & 95th St',
 'Ada St & Washington Blvd',
 'Adler Planetarium',
 'Al Raby School',
 'Albany Ave & 103rd St',
 'Albany Ave & 111th St - NW',
 'Albany Ave & 16th St',
 'Albany Ave & 26th St',
 'Albany Ave & 63rd St',
 'Albany Ave & Belmont Ave',
 'Albany Ave & Bloomingdale Ave',
 'Albany Ave & Douglas Blvd',
 'Albany Ave & Montrose Ave',
 'Altgeld Gardens',
 'Archer (Damen) Ave & 37th St',
 'Archer Ave & 43rd St',
 'Archer Park',
 'Artesian Ave & 55th St',
 'Artesian Ave & Hubbard St',
 'Ashland Ave & 13th St',
 'Ashland Ave & 45th St',
 'Ashland Ave & 45th St - midblock south',
 'Ashland Ave & 46th St',
 'Ashland Ave & 50th St',
 'Ashland Ave & 63rd St',
 'Ashland Ave & 66th St',
 'Ashland Ave & 71st St',
 'Ashland Ave & 73rd St',
 'Ashland Ave & 74th St',
 'Ashland Ave & 78th St',
 'Ashland Ave & Archer Ave',
 'Ashland Ave & Augusta Blvd',
 'Ashland Ave & Belle Plaine Ave',
 'Ashland Ave & Blackhawk St',
 'Ashland Ave & Chicago Ave',
 'Ashland Ave & Division St',
 'Ashland Ave & Garfield Blvd',
 'Ashland Ave & Grace St',
 'Ashland Ave & Grand Ave',
 'Ashland Ave & Lake St',
 'Ashland Ave & McDowell Ave',
 'Ashland Ave & Pershing Rd',
 'Ashland Ave & Wellington Ave',
 'Ashland Ave & Wrightwood Ave',
 'Augusta Blvd & Laramie Ave',
 'Austin Ave & Roscoe St',
 'Austin Ave & Wellington Ave - midblock',
 'Austin Ave & Wrightwood Ave',
 'Austin Blvd & Chicago Ave',
 'Austin Blvd & Lake St',
 'Austin Blvd & Madison St',
 'Austin Blvd & North Ave',
 'Austin Branch Chicago Public Library',
 'Avenue J & 106th St',
 'Avenue J & 112th St',
 'Avenue L & 114th St',
 'Avenue M & 132nd St',
 'Avenue O & 118th St',
 'Avenue O & 134th St',
 'Avers Ave & Archer Ave',
 'Avers Ave & Belmont Ave',
 'Avers Ave & Irving Park Rd',
 'Avers Ave & Ogden Ave',
 'Avondale Ave & Addison St',
 'Avondale Ave & Irving Park Rd',
 'Back of the Yards Park',
 'Baltimore Ave & 133rd St',
 'Baltimore Ave & 87th St',
 'Base - 2132 W Hubbard',
 'Base - 2132 W Hubbard Warehouse',
 'Bell Ave & 95th St',
 'Bennett Ave & 79th St',
 'Bennett Ave & 96th St',
 'Bensley Ave & 103rd St',
 'Benson Ave & Church St',
 'Bernard St & Elston Ave',
 'Big Marsh Park',
 'Bishop St & 46th St',
 'Bissell St & Armitage Ave',
 'Bissell St & Armitage Ave - Charging',
 'Bissell St & Armitage Ave*',
 'Blackstone Ave & Hyde Park Blvd',
 'Bloomingdale Ave & Harlem Ave',
 'Blue Island Ave & 18th St',
 'Bosworth Ave & Howard St',
 'Bradley Park',
 'Brandon Ave & 91st St',
 'Brighton Park Branch Chicago Library',
 'Broadway & Argyle St',
 'Broadway & Barry Ave',
 'Broadway & Belmont Ave',
 'Broadway & Berwyn Ave',
 'Broadway & Cornelia Ave',
 'Broadway & Granville Ave',
 'Broadway & Ridge Ave',
 'Broadway & Sheridan Rd',
 'Broadway & Thorndale Ave',
 'Broadway & Waveland Ave',
 'Broadway & Wilson - Truman College Vaccination Site',
 'Buckingham Fountain',
 'Buckingham Fountain (Temp)',
 'Budlong Woods Library',
 'Buffalo Ave & 133rd St',
 'Buffalo Ave & 89th St',
 'Burling St & Diversey Pkwy',
 'Burnham Greenway & 105th St',
 'Burnham Greenway & 112th St',
 'Burnham Harbor',
 'California & 16th St',
 'California Ave & 21st St',
 'California Ave & 23rd Pl',
 'California Ave & 26th St',
 'California Ave & 29th St',
 'California Ave & 36th St',
 'California Ave & Altgeld St',
 'California Ave & Byron St',
 'California Ave & Cortez St',
 'California Ave & Devon Ave - NE',
 'California Ave & Devon Ave - NW',
 'California Ave & Division St',
 'California Ave & Fletcher St',
 'California Ave & Francis Pl (Temp)',
 'California Ave & Lake St',
 'California Ave & Marquette Rd',
 'California Ave & Milwaukee Ave',
 'California Ave & Montrose Ave',
 'California Ave & North Ave',
 'California Ave & Ogden Ave',
 'California Ave & Pershing Rd',
 'California Ave & Touhy Ave - NW',
 'California Ave & Winona St',
 'Calumet Ave & 103rd St',
 'Calumet Ave & 18th St',
 'Calumet Ave & 21st St',
 'Calumet Ave & 33rd St',
 'Calumet Ave & 35th St',
 'Calumet Ave & 51st St',
 'Calumet Ave & 71st St',
 'Calumet Ave & Garfield Blvd',
 'Calumet Park',
 'Campbell Ave & 51st St',
 'Campbell Ave & Fullerton Ave',
 'Campbell Ave & Irving Park Rd',
 'Campbell Ave & Montrose Ave',
 'Campbell Ave & North Ave',
 'Canal St & Adams St',
 'Canal St & Harrison St',
 'Canal St & Jackson Blvd',
 'Canal St & Madison St',
 'Canal St & Monroe St',
 'Canal St & Taylor St',
 'Cannon Dr & Fullerton Ave',
 'Carpenter St & 63rd St',
 'Carpenter St & Huron St',
 'Central Ave & Chicago Ave',
 'Central Ave & Corcoran Pl',
 'Central Ave & George St',
 'Central Ave & Harrison St',
 'Central Ave & Lake St',
 'Central Ave & Madison St',
 'Central Ave & North Ave',
 'Central Ave & Parker Ave',
 'Central Ave & Roscoe St',
 'Central Park & Augusta Blvd',
 'Central Park Ave & 24th St',
 'Central Park Ave & Bloomingdale Ave',
 'Central Park Ave & Douglas Blvd',
 'Central Park Ave & Elbridge Ave',
 'Central Park Ave & North Ave',
 'Central Park Ave & Ogden Ave',
 'Central Park Ave & Ohio St',
 'Central Park Blvd & 5th Ave',
 'Central St & Girard Ave',
 'Central St Metra',
 'Chappel Ave & 71st St',
 'Chase Ave & Touhy Ave - NE',
 'Chase Ave & Touhy Ave - NW',
 'Cherry Ave & Blackhawk St',
 'Chicago Ave & Sheridan Rd',
 'Chicago Ave & Washington St',
 'Chicago State University',
 'Chopin Park',
 'Christiana Ave & 55th St',
 'Christiana Ave & Archer Ave',
 'Christiana Ave & Belmont Ave',
 'Christiana Ave & Bryn Mawr Ave',
 'Christiana Ave & Lawrence Ave',
 'Cicero Ave & Altgeld St',
 'Cicero Ave & Cortland St - midblock',
 'Cicero Ave & Flournoy St',
 'Cicero Ave & Grace St',
 'Cicero Ave & Lake St',
 'Cicero Ave & Le Moyne St - midblock',
 'Cicero Ave & North Ave',
 'Cicero Ave & Quincy St',
 'Cicero Ave & Roscoe St',
 'Cicero Ave & Wellington Ave',
 'Cicero Ave & Wrightwood Ave',
 'Cityfront Plaza Dr & Pioneer Ct',
 'Claremont Ave & 71st St',
 'Claremont Ave & Hirsch St',
 'Clarendon Ave & Gordon Ter',
 'Clarendon Ave & Junior Ter',
 'Clarendon Ave & Leland Ave',
 'Clark St & 9th St (AMLI)',
 'Clark St & Armitage Ave',
 'Clark St & Berwyn Ave',
 'Clark St & Bryn Mawr Ave',
 'Clark St & Chicago Ave',
 'Clark St & Columbia Ave',
 'Clark St & Drummond Pl',
 'Clark St & Elm St',
 'Clark St & Elmdale Ave',
 'Clark St & Grace St',
 'Clark St & Ida B Wells Dr',
 'Clark St & Jarvis Ave',
 'Clark St & Lake St',
 'Clark St & Leland Ave',
 'Clark St & Lincoln Ave',
 'Clark St & Lunt Ave',
 'Clark St & Montrose Ave',
 'Clark St & Newport St',
 'Clark St & North Ave',
 'Clark St & Randolph St',
 'Clark St & Schiller St',
 'Clark St & Schreiber Ave',
 'Clark St & Touhy Ave',
 'Clark St & Wellington Ave',
 'Clark St & Winnemac Ave',
 'Clark St & Wrightwood Ave',
 'Clifton Ave & Armitage Ave',
 'Clinton St & 18th St',
 'Clinton St & Jackson Blvd',
 'Clinton St & Lake St',
 'Clinton St & Madison St',
 'Clinton St & Polk St',
 'Clinton St & Roosevelt Rd',
 'Clinton St & Tilden St',
 'Clinton St & Washington Blvd',
 'Clybourn Ave & Division St',
 'Clyde Ave & 87th St',
 'Colfax Ave & 83rd St',
 'Columbus Dr & Randolph St',
 'Commercial Ave & 100th St',
 'Commercial Ave & 130th St',
 'Commercial Ave & 83rd St',
 'Commercial Ave & 89th St',
 'Conservatory Dr & Lake St',
 'Constance Ave & 95th St',
 'Corliss Ave & 133rd St',
 'Cornell Ave & Hyde Park Blvd',
 'Cornell Dr & Hayes Dr',
 'Cottage Grove & 85th St',
 'Cottage Grove & 86th St',
 'Cottage Grove Ave & 111th Pl',
 'Cottage Grove Ave & 111th St',
 'Cottage Grove Ave & 43rd St',
 'Cottage Grove Ave & 47th St',
 'Cottage Grove Ave & 51st St',
 'Cottage Grove Ave & 63rd St',
 'Cottage Grove Ave & 67th St',
 'Cottage Grove Ave & 71st St',
 'Cottage Grove Ave & 75th St',
 'Cottage Grove Ave & 78th St',
 'Cottage Grove Ave & 83rd St',
 'Cottage Grove Ave & 87th St',
 'Cottage Grove Ave & 91st St',
 'Cottage Grove Ave & 92nd St',
 'Cottage Grove Ave & 98th St',
 'Cottage Grove Ave & Oakwood Blvd',
 'Daley Center Plaza',
 'Damen Ave & 33rd St',
 'Damen Ave & 47th St',
 'Damen Ave & 51st St',
 'Damen Ave & 59th St',
 'Damen Ave & 74th St',
 'Damen Ave & 80th St',
 'Damen Ave & Charleston St',
 'Damen Ave & Chicago Ave',
 'Damen Ave & Clybourn Ave',
 'Damen Ave & Cortland St',
 'Damen Ave & Coulter St',
 'Damen Ave & Cullerton St',
 'Damen Ave & Division St',
 'Damen Ave & Foster Ave',
 'Damen Ave & Grand Ave',
 'Damen Ave & Leland Ave',
 'Damen Ave & Madison St',
 'Damen Ave & Melrose Ave',
 'Damen Ave & Pershing Rd',
 'Damen Ave & Pierce Ave',
 'Damen Ave & Sunnyside Ave',
 'Damen Ave & Thomas St (Augusta Blvd)',
 'Damen Ave & Wabansia Ave',
 'Damen Ave & Walnut (Lake) St',
 'Damen Ave & Wellington Ave',
 'Dauphin Ave & 103rd St',
 'Dauphin Ave & 87th St',
 'Dayton St & North Ave',
 'Dearborn Pkwy & Delaware Pl',
 'Dearborn St & Adams St',
 'Dearborn St & Erie St',
 'Dearborn St & Monroe St',
 'Dearborn St & Van Buren St',
 'Delano Ct & Roosevelt Rd',
 'Desplaines St & Jackson Blvd',
 'Desplaines St & Kinzie St',
 'Desplaines St & Randolph St',
 'Divvy Valet - Oakwood Beach',
 'Dodge Ave & Church St',
 'Dodge Ave & Main St',
 'Dodge Ave & Mulford St',
 'Dorchester Ave & 49th St',
 'Dorchester Ave & 63rd St',
 'Doty Ave & 111th St',
 'Drake Ave & Addison St',
 'Drake Ave & Montrose Ave',
 'Drexel Ave & 87th St',
 'DuSable Lake Shore Dr & Belmont Ave',
 'DuSable Lake Shore Dr & Diversey Pkwy',
 'DuSable Lake Shore Dr & Monroe St',
 'DuSable Lake Shore Dr & North Blvd',
 'DuSable Lake Shore Dr & Ohio St',
 'DuSable Lake Shore Dr & Wellington Ave',
 'DuSable Museum',
 'Dusable Harbor',
 'East End Ave & 87th St',
 'Eastlake Ter & Rogers Ave',
 'Eberhart Ave & 131st St',
 'Eberhart Ave & 61st St',
 'Eberhart Ave & 91st St',
 'Eckhart Park',
 'Eggleston Ave & 114th St',
 'Eggleston Ave & 69th St',
 'Eggleston Ave & 92nd St',
 'Eli Whitney Public School',
 'Elizabeth (May) St & Fulton St',
 'Elizabeth St & 47th St',
 'Elizabeth St & 59th St',
 'Elizabeth St & 92nd St',
 'Ellis Ave & 132nd Pl',
 'Ellis Ave & 53rd St',
 'Ellis Ave & 55th St',
 'Ellis Ave & 58th St',
 'Ellis Ave & 60th St',
 'Ellis Ave & 83rd St',
 'Elmwood Ave & Austin St',
 'Elston Ave & Cortland St',
 'Elston Ave & George St',
 'Elston Ave & Henderson St',
 'Elston Ave & Wabansia Ave',
 'Emerald Ave & 28th St',
 'Emerald Ave & 31st St',
 'Emerald Ave & 43rd St',
 'Emerald Ave & 45th St',
 'Evans Ave & 63rd St',
 'Evans Ave & 75th St',
 'Evanston Civic Center',
 'Ewing Ave & 101st St',
 'Ewing Ave & 105th St',
 'Ewing Ave & 106th St',
 'Ewing Ave & 112th St',
 'Ewing Ave & 96th St',
 'Ewing Ave & 99th St',
 'Ewing Ave & Burnham Greenway',
 'Ewing Ave & Indianapolis Ave',
 'Exchange Ave & 79th St',
 'Fairbanks Ct & Grand Ave',
 'Fairbanks St & Superior St',
 'Fairfield Ave & 44th St',
 'Fairfield Ave & Roosevelt Rd',
 'Federal St & Polk St',
 'Field Blvd & South Water St',
 'Field Museum',
 'Financial Pl & Ida B Wells Dr',
 'Forrestville Ave & 47th St',
 'Fort Dearborn Dr & 31st St',
 'Francisco Ave & 47th St',
 'Francisco Ave & Bloomingdale Ave',
 'Francisco Ave & Foster Ave',
 'Francisco Ave & Hollywood Ave',
 'Francisco Ave & Montrose Ave',
 'Franklin St & Adams St (Temp)',
 'Franklin St & Chicago Ave',
 'Franklin St & Illinois St',
 'Franklin St & Jackson Blvd',
 'Franklin St & Lake St',
 'Franklin St & Monroe St',
 'Fullerton & Monitor',
 'Glenwood Ave & Morse Ave',
 'Glenwood Ave & Touhy Ave',
 'Grand Ave & North Ave',
 'Green St & 103rd St',
 'Green St & Madison St',
 'Green St & Randolph St',
 'Green St & Randolph St*',
 'Green St & Washington Blvd',
 'Greenview Ave & Diversey Pkwy',
 'Greenview Ave & Fullerton Ave',
 'Greenview Ave & Jarvis Ave',
 'Greenwood Ave & 47th St',
 'Greenwood Ave & 79th St',
 'Greenwood Ave & 87th St',
 'Greenwood Ave & 91st St',
 'Greenwood Ave & 97th St',
 'Greenwood Ave & Lake Park Ave',
 'Hale Ave & 107th St',
 'Hale Ave & 111th St',
 'Halsted & 63rd - Kennedy-King Vaccination Site',
 'Halsted St & 102nd St',
 'Halsted St & 104th St',
 'Halsted St & 111th St',
 'Halsted St & 18th St',
 'Halsted St & 18th St (Temp)',
 'Halsted St & 21st St',
 'Halsted St & 35th St',
 'Halsted St & 37th St',
 'Halsted St & 41st St',
 'Halsted St & 47th Pl',
 'Halsted St & 51st St',
 'Halsted St & 56th St',
 'Halsted St & 59th St',
 'Halsted St & 63rd St',
 'Halsted St & 64th St',
 'Halsted St & 69th St',
 'Halsted St & 73rd St',
 'Halsted St & 76th St',
 'Halsted St & 78th St',
 'Halsted St & 80th St',
 'Halsted St & 95th St - SE',
 'Halsted St & 95th St - SW',
 'Halsted St & 96th St',
 'Halsted St & Archer Ave',
 'Halsted St & Clybourn Ave',
 'Halsted St & Dickens Ave',
 'Halsted St & Maxwell St',
 'Halsted St & North Branch St',
 'Halsted St & Polk St',
 'Halsted St & Roosevelt Rd',
 'Halsted St & Roscoe St',
 'Halsted St & Willow St',
 'Halsted St & Wrightwood Ave',
 'Hamilton Ave & 95th St',
 'Hamlin Ave & 62nd Pl',
 'Hamlin Ave & Chicago Ave',
 'Hamlin Ave & Fullerton Ave',
 'Hamlin Ave & Grand Ave',
 'Hamlin Ave & Montrose Ave',
 'Hampden Ct & Diversey Ave',
 'Harding Ave & 26th St',
 'Harding Ave & 47th St',
 'Harlem & Irving Park',
 'Harlem Ave & Grace St',
 'Harold Washington Park',
 'Harper Ave & 59th St',
 'Harper Ave & 63rd St',
 'Harriet E Sayre Public School',
 'Harvard Ave & 103rd St',
 'Hastings WH 2',
 'Hegewisch Metra Station',
 'Hermitage Ave & Polk St',
 'Hiawatha Park',
 'Homan Ave & 111th St',
 'Homan Ave & 65th St',
 'Homan Ave & Fillmore St',
 'Homewood Ave & 115th St',
 'Homewood Ave & Monterey Ave',
 'Honore St & Division St',
 'Houston Ave & 91st St',
 'Houston Ave & 92nd St',
 'Hoyne Ave & 110th Pl',
 'Hoyne Ave & 34th St',
 'Hoyne Ave & 47th St',
 'Hoyne Ave & Balmoral Ave',
 'Humboldt Blvd & Armitage Ave',
 'Hyde Park Blvd & 53rd St',
 'Hyde Park Blvd & 55th St',
 'Indiana Ave & 103rd St',
 'Indiana Ave & 133rd St',
 'Indiana Ave & 26th St',
 'Indiana Ave & 31st St',
 'Indiana Ave & 40th St',
 'Indiana Ave & Roosevelt Rd',
 'Ingleside Ave & 79th St',
 'Jefferson St & Monroe St',
 'Jeffery Blvd & 67th St',
 'Jeffery Blvd & 71st St',
 'Jeffery Blvd & 76th St',
 'Jeffery Blvd & 83rd St',
 'Jeffrey Blvd & 71st St',
 'Jonathan Y Scammon Public School',
 'Justine St & 87th St',
 'Karlov Ave & Kamerling Ave',
 'Karlov Ave & Madison St',
 'Karlov Ave & Milwaukee Ave',
 'Kedvale Ave & 63rd St',
 'Kedvale Ave & Avondale Ave',
 'Kedzie & 103rd St - East',
 'Kedzie Ave & 104th St',
 'Kedzie Ave & 110th St',
 'Kedzie Ave & 21st St',
 'Kedzie Ave & 24th St',
 'Kedzie Ave & 45th St',
 'Kedzie Ave & 48th Pl',
 'Kedzie Ave & 52nd St',
 'Kedzie Ave & 54th St - SE',
 'Kedzie Ave & 54th St - SW',
 'Kedzie Ave & 57th St',
 'Kedzie Ave & 58th St',
 'Kedzie Ave & 61st Pl',
 'Kedzie Ave & 63rd St',
 'Kedzie Ave & 64th St - SE',
 'Kedzie Ave & 64th St - SW',
 'Kedzie Ave & Archer Ave',
 'Kedzie Ave & Argyle St',
 'Kedzie Ave & Bryn Mawr Ave',
 'Kedzie Ave & Chicago Ave',
 'Kedzie Ave & Foster Ave',
 'Kedzie Ave & George St',
 'Kedzie Ave & Harrison St',
 'Kedzie Ave & Lake St',
 'Kedzie Ave & Leland Ave',
 'Kedzie Ave & Milwaukee Ave',
 'Kedzie Ave & Palmer Ct',
 'Kedzie Ave & Pershing Rd',
 'Kedzie Ave & Roosevelt Rd',
 'Keeler Ave & 55th St',
 'Keeler Ave & Roosevelt Rd',
 'Kenneth Ave & 50th St',
 'Kenneth Ave & 63rd St',
 'Kenosha & Wellington',
 'Kenton Ave & Madison St',
 'Kenton Ave & Palmer St',
 'Keystone Ave & Fullerton Ave',
 'Keystone Ave & Irving Park Rd',
 'Keystone Ave & Montrose Ave',
 'Keystone Ave & North Ave',
 'Kilbourn & Belden',
 'Kilbourn & Roscoe',
 'Kilbourn Ave & Fullerton Ave',
 'Kilbourn Ave & Irving Park Rd',
 'Kilbourn Ave & Milwaukee Ave',
 'Kildare & Cermak',
 'Kildare Ave & 26th St',
 'Kildare Ave & 47th St',
 'Kildare Ave & 55th St',
 'Kildare Ave & 63rd St',
 'Kildare Ave & Chicago Ave',
 'Kildare Ave & Division Ave',
 'Kildare Ave & Division St',
 'Kildare Ave & Montrose Ave',
 'Kildare Ave & Washignton Blvd',
 'Kilpatrick Ave & Grand Ave',
 'Kilpatrick Ave & Parker Ave',
 'Kimball Ave & Belmont Ave',
 'Kimball Ave & Carmen Ave',
 'Kimbark Ave & 53rd St',
 'Kimbark Ave & 63rd St',
 'Kimbark Ave & 67th St',
 'Kingsbury St & Erie St',
 'Kingsbury St & Kinzie St',
 'Knox Ave & Montrose Ave',
 'Kolin Ave & Archer Ave',
 'Komensky Ave & 31st St',
 'Komensky Ave & 55th St',
 'Komensky Ave & 59th St',
 'Kosciuszko Park',
 'Kostner Ave & 63rd St',
 'Kostner Ave & Adams St',
 'Kostner Ave & Armitage Ave',
 'Kostner Ave & Lake St',
 'Kostner Ave & North Ave',
 'Kostner Ave & Wrightwood Ave',
 'La Villita Park (Albany/30th)',
 'LaSalle Dr & Huron St',
 'LaSalle St & Adams St',
 'LaSalle St & Illinois St',
 'LaSalle St & Jackson Blvd',
 'LaSalle St & Washington St',
 'Lafayette Ave & 119th St',
 'Lafayette Ave & 87th St - NW',
 'Lafayette Ave & 87th St - SW',
 'Lafayette Ave & 95th St',
 'Laflin St & 51st St',
 'Laflin St & 79th St',
 'Laflin St & Cullerton St',
 'Lake Park Ave & 35th St',
 'Lake Park Ave & 44th St',
 'Lake Park Ave & 47th St',
 'Lake Park Ave & 53rd St',
 'Lake Park Ave & 56th St',
 'Lakefront Trail & Bryn Mawr Ave',
 'Lakefront Trail & Wilson Ave',
 'Lakeview Ave & Fullerton Pkwy',
 'Lamon Ave & Archer Ave',
 'Lamon Ave & Armitage Ave',
 'Lamon Ave & Belmont Ave',
 'Lamon Ave & Chicago Ave',
 'Langley Ave & 105th Pl',
 'Langley Ave & 79th St',
 'Laramie Ave & Belmont Ave',
 'Laramie Ave & Fullerton Ave',
 'Laramie Ave & Gladys Ave',
 'Laramie Ave & Grand Ave',
 'Laramie Ave & Kinzie St',
 'Laramie Ave & Madison St',
 'Larrabee St & Armitage Ave',
 'Larrabee St & Division St',
 'Larrabee St & Kingsbury St',
 'Larrabee St & Menomonee St',
 'Larrabee St & North Ave',
 'Larrabee St & Oak St',
 'Larrabee St & Webster Ave',
 'Latrobe Ave & Chicago Ave',
 'Latrobe Ave & Lake St',
 'Lavergne & Fullerton',
 'Lavergne Ave & 46th St',
 'Lavergne Ave & Division St',
 'Lawler Ave & 50th St',
 'Lawndale Ave & 111th St',
 'Lawndale Ave & 16th St',
 'Lawndale Ave & 30th St',
 'Lawndale Ave & Diversey Ave',
 'Lawndale Ave & Polk St',
 'Lawrence Ave & 103rd St',
 'Leamington Ave & Hirsch St',
 'Leavitt St & Addison St',
 'Leavitt St & Archer Ave',
 'Leavitt St & Armitage Ave',
 'Leavitt St & Belmont Ave',
 'Leavitt St & Chicago Ave',
 'Leavitt St & Division St',
 'Leavitt St & Lawrence Ave',
 'Leavitt St & North Ave',
 'Legler Regional Library',
 'Lincoln Ave & Addison St',
 'Lincoln Ave & Balmoral Ave',
 'Lincoln Ave & Belle Plaine Ave',
 'Lincoln Ave & Belmont Ave',
 'Lincoln Ave & Belmont Ave (Temp)',
 'Lincoln Ave & Diversey Pkwy',
 'Lincoln Ave & Fullerton Ave',
 'Lincoln Ave & Peterson Ave',
 'Lincoln Ave & Roscoe St',
 'Lincoln Ave & Roscoe St*',
 'Lincoln Ave & Sunnyside Ave',
 'Lincoln Ave & Waveland Ave',
 'Lincoln Ave & Winona St',
 'Lincoln Park Conservatory',
 'Lincolnwood Dr & Central St',
 'Linder Ave & Belmont Ave',
 'Lockwood Ave & Wrightwood Ave',
 'Logan Blvd & Elston Ave',
 'Long & Irving Park',
 'Long Ave & Belden Ave',
 'Long Ave & Belmont Ave',
 'Long Ave & North Ave',
 'Longwood Dr & 111th St',
 'Loomis Blvd & 83rd St',
 'Loomis Blvd & 84th St',
 'Loomis St & 87th St',
 'Loomis St & 89th St',
 'Loomis St & Archer Ave',
 'Loomis St & Jackson Blvd',
 'Loomis St & Lexington St',
 'Lorel Ave & Chicago Ave',
 'Lowe Ave & 98th St',
 'Lowell Ave & Elston Ave',
 'MLK Jr Dr & 29th St',
 'MLK Jr Dr & 47th St',
 'MLK Jr Dr & 56th St',
 'MLK Jr Dr & 63rd St',
 'MLK Jr Dr & 83rd St',
 'MLK Jr Dr & Pershing Rd',
 'MTV Hubbard St',
 'Mackinaw Ave & 106th St',
 'Mackinaw Ave & 108th St',
 'Mackinaw Ave & 85th St',
 'Major Ave & Bloomingdale Ave',
 'Major Taylor Trail & 115th St',
 'Major Taylor Trail & 124th St',
 'Malcolm X College Vaccination Site',
 'Manor Ave & Leland Ave',
 'Maplewood Ave & 59th St',
 'Maplewood Ave & Peterson Ave',
 'Marine Dr & Ainslie St',

# Check the Amount of Ride types and Members

In [41]:
df_new['rideable_type'].value_counts()

classic_bike     2850329
electric_bike    1433772
docked_bike       204232
Name: rideable_type, dtype: int64

In [42]:
df_new['member_casual'].value_counts()

member    2635450
casual    1852883
Name: member_casual, dtype: int64

In [43]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4488333 entries, 0 to 4560145
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       category
 2   started_at          datetime64[ns]
 3   ended_at            datetime64[ns]
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       category
 13  member_type         category
 14  ride_length         float64
 15  lat                 float64
 16  lng                 float64
 17  ride_distance       float64
 18  time_of_day         int8
 19  day_of_week         category
 20  month               category
 21  season              category
dtypes: category(6), datetime64[ns](2), float64(8), int8(1), object(5)
memory usage: 577.9+ MB

In [45]:
df_new.to_csv('Cyclistic.csv')